### Book refered: "Game Theory" by Giacomo Bonano

In [1]:
import numpy as np
import pandas as pd

#### Prisoner's Dilemma game

##### Python program that determines the Dominant strategies and equilibrium of the Prisoner's Dilemma Game

In [28]:
## Payoffs for Player 1
Doug=np.array(([2, 0], [3, 1]))
print(pd.DataFrame(Doug))
print(" ")
## Payoffs for player 2
Ed=np.array(([2, 3], [0, 1]))
print(pd.DataFrame(Ed))

def PrisonersDilemma(Player1, Player2):
    m1=max(Player1[:, 0])
    m2=max(Player1[:, 1])
    
    m3=max(Player2[0, :])
    m4=max(Player2[1, :])
    
    
    ## Player1's dominant strategy
    if m1==Player1[0, 0] and m2==Player1[0, 1]: print("Player1's dominant strategy is to give normal effort")
    elif m1==Player1[1, 0] and m2==Player1[1, 1]: print("Player1's dominant strategy is to give extra effort")
    else: print("Player1 has no dominant strategy")
        
    ## Player2's dominant strategy
    if m3==Player2[0, 0] and m4==Player2[1, 0]: print("Player2's dominant strategy is to give normal effort")
    elif m3==Player2[0, 1] and m4==Player2[1, 1]: print("Player2's dominant strategy is to give extra effort")
    else: print("Player2 has no dominant strategy")
        
    ##To find the dominant strategy equilibrium of the game
    if m1==Player1[0, 0] and m2==Player1[0, 1] and m3==Player2[0, 0] and m4==Player2[1, 0]: return ("Normal", "Normal")
    elif m1==Player1[0, 0] and m2==Player1[0, 1] and m3==Player2[0, 1] and m4==Player2[1, 1]: return ("Normal", "Extra")
    elif m1==Player1[1, 0] and m2==Player1[1, 1] and m3==Player2[0, 0] and m4==Player2[1, 0]: return ("Extra", "Normal")
    elif m1==Player1[1, 0] and m2==Player1[1, 1] and m3==Player2[0, 1] and m4==Player2[1, 1]: return ("Extra", "Extra")
    else: return "No dominant strategy equilibrium "
    
PrisonersDilemma(Doug, Ed)

   0  1
0  2  0
1  3  1
 
   0  1
0  2  3
1  0  1
Player1's dominant strategy is to give extra effort
Player2's dominant strategy is to give extra effort


('Extra', 'Extra')

##### The Iterated Deletion of Strictly Dominated Strategies (IDSDS Algorithm)

In [15]:
## Payoffs for player 1
#P1=np.array(([6, 4, 4, 3], [5, 6, 0, 5], [5, 3, 6, 4], [2, 2, 3, 6]))
#print(pd.DataFrame(P1))
#print(" ")

## Payoffs for player 2
#P2=np.array(([3, 4, 1, 0], [4, 3, 2, 1], [0, 2, 1, 0], [0, 3, 3, 1]))
#print(pd.DataFrame(P2))

#Ex. 2.11
P1=np.array(([8, 0, 3], [3, 2, 4], [2, 1, 3]))
P2=np.array(([6, 9, 8], [2, 1, 3], [8, 5, 1]))
def IDSDS(P1, P2):
    check1, check2=0, 0
    while True:
        for i in range(len(P1)):
            for j in range(len(P1)):
                if list(P1[i, :]<P1[j, :]).count(True)==len(P1[0]):
                    P1=np.delete(P1, (i), axis=0)
                    P2=np.delete(P2, (i), axis=0)
                    check1=1
                    break
            if check1==1: break
        
        if check1==0:
            for i in range(len(P2[0])):
                for j in range(len(P2[0])):
                    if list(P2[:, i]<P2[:, j]).count(True)==len(P2):
                        P2=np.delete(P2, (i), axis=1)
                        P1=np.delete(P1, (i), axis=1)
                        check2=1
                        break
                if check2==1:break
        
        print(P1)
        print(P2)
        if check1==0 and check2==0: break
        check1, check2=0, 0
    
    return (P1, P2)

IDSDS(P1, P2)

[[8 0 3]
 [3 2 4]]
[[6 9 8]
 [2 1 3]]
[[0 3]
 [2 4]]
[[9 8]
 [1 3]]
[[2 4]]
[[1 3]]
[[4]]
[[3]]
[[4]]
[[3]]


(array([[4]]), array([[3]]))

#### A perfect information game

##### Game based on Figure 3.7 mentioned in the book: This program determines the Nash equilibria from the strategic form of the perfect information game

In [36]:
## Payoffs for Player 1
Player1=np.array(([2, 2, 0, 0], [2, 2, 0, 0], [3, 1, 3, 1], [3, 1, 3, 1]))
print(pd.DataFrame(Player1))
print(" ")
## Payoffs for player 2
Player2=np.array(([1, 1, 0, 0], [1, 1, 0, 0], [1, 2, 1, 2], [1, 0, 1, 0]))
print(pd.DataFrame(Player2))

L1=[]
L2=[]

for i in range(4):
    a=Player1[:, i]
    M=max(a)
    for j in range(4):
        if a[j]==M: L1+=[[j, i], ]

for i in range(4):
    a=Player2[i, :]
    M=max(a)
    for j in range(4):
        if a[j]==M: L2+=[[i, j], ]

N=[i for i in L1 if i in L2]

I1={0:'ag', 1:'ah', 2:'bg', 3:'bh'}
I2={0:'ce', 1:'cf', 2:'de', 3:'df'}

Nash=[(I1[i], I2[j]) for [i, j] in N]
## The Nash equilibria
Nash

   0  1  2  3
0  2  2  0  0
1  2  2  0  0
2  3  1  3  1
3  3  1  3  1
 
   0  1  2  3
0  1  1  0  0
1  1  1  0  0
2  1  2  1  2
3  1  0  1  0


[('bh', 'ce'), ('ag', 'cf'), ('ah', 'cf'), ('bh', 'de'), ('bg', 'df')]

#### General Dynamic Games

##### Exercise 4.10: Find the Nash equilibria and the subgame-perfect equilibria of the game shown in Figure 4.24

In [48]:
## First we consider the subgame that starts at decision node of player 2 after following choice A of Player 1

#Payoffs for player 2 
P2=np.array(([0, 2, 1], [1, 1, 2], [0, 0, 3]))
print(pd.DataFrame(P2))
print(" ")

#Payoffs for player 3
P3=np.array(([0, 0, 1], [0, 2, 1], [1, 1, 2]))
print(pd.DataFrame(P3))

##We find the Nash equilibria for this proper subgame
L1=[]
L2=[]

for i in range(len(P2)):
    a=P2[:, i]
    M=max(a)
    for j in range(len(a)):
        if a[j]==M: L1+=[[j, i], ]

for i in range(len(P3)):
    a=P3[i, :]
    M=max(a)
    for j in range(len(a)):
        if a[j]==M: L2+=[[i, j], ]

N=[i for i in L1 if i in L2]

I2={0:'C', 1:'D', 2:'E'}
I3={0:'F', 1:'G', 2:'H'}

Nash1=[(I2[i], I3[j]) for [i, j] in N]
## The Nash equilibria
print(Nash1)

## Now we consider the subgame that starts at decision node of player 2 after following choice B of Player 1
#Payoffs for player 2 
P2=np.array(([2, 1], [0, 1]))
print(pd.DataFrame(P2))
print(" ")

#Payoffs for player 3
P3=np.array(([1, 0], [0, 1]))
print(pd.DataFrame(P3))

##We find the Nash equilibria for this proper subgame
L1=[]
L2=[]

for i in range(len(P2)):
    a=P2[:, i]
    M=max(a)
    for j in range(len(a)):
        if a[j]==M: L1+=[[j, i], ]

for i in range(len(P3)):
    a=P3[i, :]
    M=max(a)
    for j in range(len(a)):
        if a[j]==M: L2+=[[i, j], ]

N=[i for i in L1 if i in L2]

I2={0:'L', 1:'M'}
I3={0:'P', 1:'R'}

Nash2=[(I2[i], I3[j]) for [i, j] in N]
## The Nash equilibria
print(Nash2)

## There are two subgame perfect equilibria
[['A', (Nash1[0][0], Nash2[0][0]), (Nash1[0][1], Nash2[0][1])], ['B', (Nash1[0][0], Nash2[1][0]), (Nash1[0][1], Nash2[1][1])]]

   0  1  2
0  0  2  1
1  1  1  2
2  0  0  3
 
   0  1  2
0  0  0  1
1  0  2  1
2  1  1  2
[('E', 'H')]
   0  1
0  2  1
1  0  1
 
   0  1
0  1  0
1  0  1
[('L', 'P'), ('M', 'R')]


[['A', ('E', 'L'), ('H', 'P')], ['B', ('E', 'M'), ('H', 'R')]]

#### Expected Utility Theory

##### Program to evaluate a simple lottery corresponding to a given compound lottery C

In [75]:
#C=[[[1/3, 1/6, 1/3, 1/6], 1/2], [[1, 0, 0, 0], 1/4], [[1/5, 0, 1/5, 3/5], 1/4]]

#Exercise 5.12
C=[[[2/5, 1/10, 3/10, 1/5], 1/8], [[0, 1, 0, 0], 1/4], [[1/5, 0, 1/5, 3/5], 1/8], [[0, 1/3, 2/3, 0], 1/2]]

def simpLottery(C):
    r=len(C)
    m=len(C[0][0])
    x=[]
    P=[]
    
    for i in range(r):
        x+=[C[i][0], ]
        P+=[C[i][1], ]
    print(x)
    print(P)
    L=[]
    
    for i in range(m):
        q=0
        for j in range(r): q+=P[j]*x[j][i]
        L+=[q, ]
    
    return L

simpLottery(C)

[[0.4, 0.1, 0.3, 0.2], [0, 1, 0, 0], [0.2, 0, 0.2, 0.6], [0, 0.3333333333333333, 0.6666666666666666, 0]]
[0.125, 0.25, 0.125, 0.5]


[0.07500000000000001, 0.4291666666666667, 0.3958333333333333, 0.1]